#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Oct 07 12:13:41 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
